version: '3.7'

services:
  redis:
    image: redis:5.0.3-alpine
    restart: always
    command: --bind 0.0.0.0 --notify-keyspace-events Kge$$ --requirepass "${REDIS_PASSWORD}"
  app_1:
    image: node:11.9.0-alpine
    user: "node"
    environment:
      - REDIS_URL=redis://:${REDIS_PASSWORD}@redis/0
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ./src:/home/node/app
    working_dir: /home/node/app
    depends_on:
      - redis
    command: ["npm", "start"]
  app_2:
    image: node:11.9.0-alpine
    user: "node"
    environment:
      - REDIS_URL=redis://:${REDIS_PASSWORD}@redis/0
    restart: always
    ports:
      - 8081:8080
    volumes:
      - ./src:/home/node/app
    working_dir: /home/node/app
    depends_on:
      - redis
    command: ["npm", "start"]
